const productos = [
  {
    id: 1,
    nombre: "rhcp_camisa 1",
    tipo: "camisa",
    desc: "Camisa de Red Hot Chili Peppers",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/rhcp/rhcp_camisa_1.webp",
    cantidad: 1,
  },
  {
    id: 2,
    nombre: "rhcp_camisa 2",
    tipo: "camisa",
    desc: "Camisa de Red Hot Chili Peppers",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/rhcp/rhcp_camisa_2.webp",
    cantidad: 1,
  },
  {
    id: 3,
    nombre: "rhcp_camisa 3",
    tipo: "camisa",
    desc: "Camisa de Red Hot Chili Peppers",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/rhcp/rhcp_camisa_3.webp",
    cantidad: 1,
  },
  {
    id: 4,
    nombre: "rhcp_taza 1",
    tipo: "taza",
    desc: "Taza de Red Hot Chili Peppers",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/rhcp/rhcp_taza_1.jpeg",
    cantidad: 1,
  },
  {
    id: 5,
    nombre: "rhcp_taza 2",
    tipo: "taza",
    desc: "Taza de Red Hot Chili Peppers",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/rhcp/rhcp_taza_2.jpeg",
    cantidad: 1,
  },
  {
    id: 6,
    nombre: "rhcp_taza 3",
    tipo: "taza",
    desc: "Taza de Red Hot Chili Peppers",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/rhcp/rhcp_taza_3.webp",
    cantidad: 1,
  },
  {
    id: 7,
    nombre: "rhcp_llavero 1",
    tipo: "llavero",
    desc: "Llavero de Red Hot Chili Peppers",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/rhcp/rhcp_llavero_1.webp",
    cantidad: 1,
  },
  {
    id: 8,
    nombre: "rhcp_llavero 2",
    tipo: "llavero",
    desc: "Llavero de Red Hot Chili Peppers",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/rhcp/rhcp_llavero_2.webp",
    cantidad: 1,
  },
  {
    id: 9,
    nombre: "rhcp_llavero 3",
    tipo: "llavero",
    desc: "Llavero de Red Hot Chili Peppers",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/rhcp/rhcp_llavero_3.jpeg",
    cantidad: 1,
  },

  {
    id: 10,
    nombre: "queen_camisa 1",
    tipo: "camisa",
    desc: "Camisa de Queen",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/queen/queen_camisa_1.jpeg",
    cantidad: 1,
  },
  {
    id: 11,
    nombre: "queen_camisa 2",
    tipo: "camisa",
    desc: "Camisa de Queen",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/queen/queen_camisa_2.jpeg",
    cantidad: 1,
  },
  {
    id: 12,
    nombre: "queen_camisa 3",
    tipo: "camisa",
    desc: "Camisa de Queen",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/queen/queen_camisa_3.jpeg",
    cantidad: 1,
  },
  {
    id: 13,
    nombre: "queen_taza 1",
    tipo: "taza",
    desc: "Taza de Queen",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/queen/queen_taza_1.jpeg",
    cantidad: 1,
  },
  {
    id: 14,
    nombre: "queen_taza 2",
    tipo: "taza",
    desc: "Taza de Queen",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/queen/queen_taza_2.jpeg",
    cantidad: 1,
  },
  {
    id: 15,
    nombre: "queen_taza 3",
    tipo: "taza",
    desc: "Taza de Queen",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/queen/queen_taza_3.jpeg",
    cantidad: 1,
  },
  {
    id: 16,
    nombre: "queen_llavero 1",
    tipo: "llavero",
    desc: "Llavero de Queen",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/queen/queen_llavero_1.jpeg",
    cantidad: 1,
  },
  {
    id: 17,
    nombre: "queen_llavero 2",
    tipo: "llavero",
    desc: "Llavero de Queen",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/queen/queen_llavero_2.jpeg",
    cantidad: 1,
  },
  {
    id: 18,
    nombre: "queen_llavero 3",
    tipo: "llavero",
    desc: "Llavero de Queen",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/queen/queen_llavero_3.jpeg",
    cantidad: 1,
  },

  {
    id: 19,
    nombre: "metallica_camisa 1",
    tipo: "camisa",
    desc: "Camisa de Metallica",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/metallica/metallica_camisa_1.jpeg",
    cantidad: 1,
  },
  {
    id: 20,
    nombre: "metallica_camisa 2",
    tipo: "camisa",
    desc: "Camisa de Metallica",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/metallica/metallica_camisa_2.jpeg",
    cantidad: 1,
  },
  {
    id: 21,
    nombre: "metallica_camisa 3",
    tipo: "camisa",
    desc: "Camisa de Metallica",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/metallica/metallica_camisa_3.jpeg",
    cantidad: 1,
  },
  {
    id: 22,
    nombre: "metallica_taza 1",
    tipo: "taza",
    desc: "Taza de Metallica",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/metallica/metallica_taza_1.jpeg",
    cantidad: 1,
  },
  {
    id: 23,
    nombre: "metallica_taza 1",
    tipo: "taza",
    desc: "Taza de Metallica",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/metallica/metallica_taza_2.jpeg",
    cantidad: 1,
  },
  {
    id: 24,
    nombre: "metallica_taza 3",
    tipo: "taza",
    desc: "Taza de Metallica",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/metallica/metallica_taza_3.jpeg",
    cantidad: 1,
  },
  {
    id: 25,
    nombre: "metallica_llavero 1",
    tipo: "llavero",
    desc: "Llavero de Metallica",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/metallica/metallica_llavero_1.webp",
    cantidad: 1,
  },
  {
    id: 26,
    nombre: "metallica_llavero 2",
    tipo: "llavero",
    desc: "Llavero de Metallica",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/metallica/metallica_llavero_2.jpg",
    cantidad: 1,
  },
  {
    id: 27,
    nombre: "metallica_llavero 3",
    tipo: "llavero",
    desc: "Llavero de Metallica",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/metallica/metallica_llavero_3.jpeg",
    cantidad: 1,
  },

  {
    id: 28,
    nombre: "limp_camisa 1",
    tipo: "camisa",
    desc: "Camisa de Limp Bizkit",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/limp/limp_camisa_1.jpeg",
    cantidad: 1,
  },
  {
    id: 29,
    nombre: "limp_camisa 2",
    tipo: "camisa",
    desc: "Camisa de Limp Bizkit",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/limp/limp_camisa_2.jpeg",
    cantidad: 1,
  },
  {
    id: 30,
    nombre: "limp_camisa 3",
    tipo: "camisa",
    desc: "Camisa de Limp Bizkit",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/limp/limp_camisa_3.jpeg",
    cantidad: 1,
  },
  {
    id: 31,
    nombre: "limp_taza 1",
    tipo: "taza",
    desc: "Taza de Limp Bizkit",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/limp/limp_taza_1.jpeg",
    cantidad: 1,
  },
  {
    id: 32,
    nombre: "limp_taza 1",
    tipo: "taza",
    desc: "Taza de Limp Bizkit",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/limp/limp_taza_2.jpeg",
    cantidad: 1,
  },
  {
    id: 33,
    nombre: "limp_taza 3",
    tipo: "taza",
    desc: "Taza de Limp Bizkit",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/limp/limp_taza_3.jpeg",
    cantidad: 1,
  },
  {
    id: 34,
    nombre: "limp_llavero 1",
    tipo: "llavero",
    desc: "Llavero de Limp Bizkit",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/limp/limp_llavero_1.jpeg",
    cantidad: 1,
  },
  {
    id: 35,
    nombre: "limp_llavero 2",
    tipo: "llavero",
    desc: "Llavero de Limp Bizkit",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/limp/limp_llavero_2.jpeg",
    cantidad: 1,
  },
  {
    id: 36,
    nombre: "limp_llavero 3",
    tipo: "llavero",
    desc: "Llavero de Limp Bizkit",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/limp/limp_llavero_3.jpeg",
    cantidad: 1,
  },

  {
    id: 37,
    nombre: "incubus_camisa 1",
    tipo: "camisa",
    desc: "Camisa de Incubus",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/incubus/incubus_camisa_1.jpeg",
    cantidad: 1,
  },
  {
    id: 38,
    nombre: "incubus_camisa 2",
    tipo: "camisa",
    desc: "Camisa de Incubus",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/incubus/incubus_camisa_2.jpeg",
    cantidad: 1,
  },
  {
    id: 39,
    nombre: "incubus_camisa 3",
    tipo: "camisa",
    desc: "Camisa de Incubus",
    precio: 15000,
    talla: "M",
    imagen: "../img/stock/incubus/incubus_camisa_3.jpeg",
    cantidad: 1,
  },
  {
    id: 40,
    nombre: "incubus_taza 1",
    tipo: "taza",
    desc: "Taza de Incubus",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/incubus/incubus_taza_1.jpeg",
    cantidad: 1,
  },
  {
    id: 41,
    nombre: "incubus_taza 1",
    tipo: "taza",
    desc: "Taza de Incubus",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/incubus/incubus_taza_2.jpeg",
    cantidad: 1,
  },
  {
    id: 42,
    nombre: "incubus_taza 3",
    tipo: "taza",
    desc: "Taza de Incubus",
    precio: 8000,
    talla: "Media",
    imagen: "../img/stock/incubus/incubus_taza_3.jpeg",
    cantidad: 1,
  },
  {
    id: 43,
    nombre: "incubus_llavero 1",
    tipo: "llavero",
    desc: "Llavero de Incubus",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/incubus/incubus_llavero_1.jpeg",
    cantidad: 1,
  },
  {
    id: 44,
    nombre: "incubus_llavero 2",
    tipo: "llavero",
    desc: "Llavero de Incubus",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/incubus/incubus_llavero_2.jpeg",
    cantidad: 1,
  },
  {
    id: 45,
    nombre: "incubus_llavero 3",
    tipo: "llavero",
    desc: "Llavero de Incubus",
    precio: 5000,
    talla: "Pequeño",
    imagen: "../img/stock/incubus/incubus_llavero_3.jpeg",
    cantidad: 1,
  },
];
